const DISPLAY_WIDGET = 'DISPLAY_WIDGET';
const CLOSE_WIDGET = 'CLOSE_WIDGET';
const ADD_NOTE = 'ADD_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';

export {
  DISPLAY_WIDGET,
  CLOSE_WIDGET,
  ADD_NOTE,
  DELETE_NOTE,
};
